@echo off
rem Generated by Altap Salamander, https://www.altap.cz
rem name=tor+.zip
rem crc32=9D34F51A
rem time=2023-1-4 13:35:07
echo This batch file will recreate the file 'tor+.zip'.
echo Press Ctrl-C to quit.
pause
copy /b "tor+.zip.001"+"tor+.zip.002"+"tor+.zip.003" "tor+.zip"
copy /b "tor+.zip"+"tor+.zip.004" "tor+.zip"
